name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        java-version:
          - '17'
          - '21'
        os:
          - ubuntu-latest
          - windows-latest
      # in case one combination fails, we still want to see results from others
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        if: ${{ matrix.java-version == '17' && matrix.os == 'ubuntu-latest' }}
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./build/reports/kover/report.xml

      - name: Temporarily set snapshot version
        if: ${{ github.event_name == 'push' && matrix.java-version == '17' && matrix.os == 'ubuntu-latest' }}
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'release_version'
          value: 0-SNAPSHOT

      - name: Publish snapshot to Maven Central
        if: ${{ github.event_name == 'push' && matrix.java-version == '17' && matrix.os == 'ubuntu-latest' }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGKEY}}
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD}}
        run: ./gradlew publishToSonatype

  qodana:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run static code analysis
        uses: JetBrains/qodana-action@v2025.2.2

      - name: Upload static code analysis results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
